# Generated by Django 5.0.3 on 2025-12-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='angkatan',
            field=models.CharField(max_length=4),
        ),
    ]
